steps:
  release:
    image: node:18
    environment:
      NPM_ACCESS_TOKEN:
        from_secret: npm_access_token
    commands:
      - npm install -g pnpm@10.32.0
      - pnpm install --frozen-lockfile
      - npm config set //registry.npmjs.org/:_authToken $NPM_ACCESS_TOKEN
      - cp README.md appuniversum/README.md # Copy the readme before publishing so it's visible on npmjs.com
      - pnpm --filter @appuniversum/ember-appuniversum publish --no-git-checks
when:
  event: tag
  ref: refs/tags/v*
